version: 3

tasks:
  build:
    cmds:
      - odin build src/ -out:target/orderbook -o:speed -error-pos-style:unix
    sources:
      - ./src/**/*.odin
    generates:
      - target/orderbook
    silent: true

  run:
    cmds:
      - ./target/orderbook
    deps:
      - build
    silent: true

  test:
    cmds:
      # - clear
      - odin test src/ -out:target/orderbook-test -error-pos-style:unix
    sources:
      - ./src/**/*.odin
    generates:
      - ./target/orderbook-test
    silent: true
    
  clean:
    cmds:
      - rm -r ./target/*
    silent: true

  update:
    cmds:
      - git subtree pull --prefix money https://github.com/freergit/money.git main --squash
      